
import turtle
####screen=turtle.Screen()
####screen.setup(600,600)
####screen.bgcolor("red")
####jaymit = turtle.Turtle()
####jaymit.forward(300)
####screen.bgcolor("orange")
####jaymit.left(180)
####jaymit.forward(600)
####screen.reset()
####screen.bgcolor("yellow")
####screen=turtle.Screen()
####screen.setup(600,600)
####screen.bgcolor("green")
####jaymit.forward(300)
####screen.bgcolor("blue")
####jaymit.left(180)
####jaymit.forward(600)
####screen.reset()
####screen.bgcolor("purple")


##james=turtle.Turtle()
##james.begin_fill()
##james.fillcolor("red")
##james.pencolor("black")
##james.circle(100)
##james.end_fill()
##james.left(60)

##james.begin_fill()
##james.fillcolor("orange")
##james.pencolor("black")
##james.circle(100)
##james.end_fill()
##james.left(60)

##james.begin_fill()
##james.fillcolor("yellow")
##james.pencolor("black")
##james.circle(100)
##james.end_fill()
##james.left(60)

##james.begin_fill()
##james.fillcolor("green")
##james.pencolor("black")
##james.circle(100)
##james.end_fill()
##james.left(60)

##james.begin_fill()
##james.fillcolor("blue")
##james.pencolor("black")
##james.circle(100)
##james.end_fill()
##james.left(60)

##james.begin_fill()
##james.fillcolor("purple")
##james.pencolor("black")
##james.circle(100)
##james.end_fill()
##james.left(60)


james=turtle.Turtle()
james.pensize(10)
james.begin_fill()
james.fillcolor("red")
james.goto(0,0)
james.forward(100)
james.left(90)
james.forward(100)
james.left(90)
james.forward(100)
james.left(90)
james.forward(100)
james.end_fill()

james.penup()
james.pensize(5)
james.goto(0,300)
james.pendown()
james.fillcolor("orange")
james.begin_fill()
james.circle(50)
james.end_fill()


james.penup()
james.pensize(10)
james.goto(0,-300)
james.pendown()
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)


james.penup()
james.pensize(5)
james.goto(100,-280)
james.pendown()
james.forward(100)
james.left(120)
james.forward(100)
james.left(120)
james.forward(100)
james.left(120)


james.penup()
james.pensize(12)
james.pencolor("black")
james.fillcolor("pink")
james.begin_fill()
james.goto(400,-450)
james.pendown()

james.left(90)
james.forward(200)
james.left(90)
james.forward(200)
james.left(90)
james.forward(200)
james.left(90)
james.forward(200)
james.end_fill()
james.penup()


james.pensize(10)
james.begin_fill()
james.fillcolor("red")
james.goto(200,-200)
james.pendown()
james.forward(100)
james.left(90)
james.forward(100)
james.left(90)
james.forward(100)
james.left(90)
james.forward(100)
james.end_fill()


james.penup()
james.pensize(5)
james.goto(100,-100)
james.pendown()
james.fillcolor("orange")
james.begin_fill()
james.circle(50)
james.end_fill()


james.penup()
james.pensize(10)
james.goto(350,-300)
james.pendown()
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)
james.left(60)
james.forward(20)


james.penup()
james.pensize(5)
james.goto(500,-500)
james.pendown()
james.forward(100)
james.left(120)
james.forward(100)
james.left(120)
james.forward(100)
james.left(120)

james.penup()
james.pensize(12)
james.pencolor("black")
james.fillcolor("pink")
james.begin_fill()
james.goto(400,-450)
james.pendown()
james.end_fill()


james.penup()
james.pensize(13)
james.pencolor("black")
james.fillcolor("blue")
james.left(90)
james.forward(200)
james.left(90)
james.forward(200)
james.left(90)
james.forward(200)
james.left(90)
james.forward(200)
james.end_fill()
james.penup()















